// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nupdfznxiwclgdkujjub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51cGRmem54aXdjbGdka3VqanViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU4MTI0NTgsImV4cCI6MjA1MTM4ODQ1OH0.yTIiWvfKOo9d0WpFybAoWNcw9uh-YN5WmbLvODCglQI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);